---

- name: Generate random secrets for Swarm services and store them in a variables file
  hosts: localhost
  gather_facts: false
  roles:
    - name: bob1de.webswarm.generate_secrets
      # The default path is inside {{ playbook_dir }}, which makes no sense for a
      # playbook part of a collection, hence a path relative to working directory
      # is set unless overridden (e.g. via -e option).
      secrets_file: "vars/webswarm-secrets.yml"
