---

- name: Generate random secrets for Swarm services and store them in a variables file
  hosts: localhost
  gather_facts: false
  roles:
    - name: bob1de.webswarm.generate_secrets
      # The default path is inside {{ playbook_dir }}, which makes no sense for a
      # playbook part of a collection.
      secrets_file: "{{ secrets_file | default('vars/webswarm-secrets.yml') }}"
